class Screen
    def self.welcome
        puts '40'
        puts '              Git Forknite!'
        puts ''
        puts ''
        puts ''
        puts ''
        puts ''
        puts ''
        puts ''
        puts ''
        puts ''
        puts ''
        puts '              Enter number of players between 2 and 5!'
        puts ''
    end
    def self.two
        puts ''
        puts ''
        puts ''
        puts '                                                               / \                 / \                                      '
        puts '                                                              |   |               |   |                                     '
        puts '                                                               \ /                 \ /                                      '
        puts '                                                                |                   |                                       '
        puts '                                                              / | \               / | \                                     '
        puts '                                                             /  |  \             /  |  \                                    '
        puts '                                                                |                   |                                       '
        puts '                                                               / \                 / \                                      '
        puts '                                                              /   \               /   \                                     '
        puts '                                                             /     \             /     \                                    '
        puts '                                        ------------------------------------------------------------------------------------'
    end
    def self.three
        puts ''
        puts ''
        puts ''
        puts '                                                          / \                 / \                 / \                       '
        puts '                                                         |   |               |   |               |   |                      '
        puts '                                                          \ /                 \ /                 \ /                       '
        puts '                                                           |                   |                   |                        '
        puts '                                                         / | \               / | \               / | \                      '
        puts '                                                        /  |  \             /  |  \             /  |  \                     '
        puts '                                                           |                   |                   |                        '
        puts '                                                          / \                 / \                 / \                       '
        puts '                                                         /   \               /   \               /   \                      '
        puts '                                                        /     \             /     \             /     \                     '
        puts '                                        ------------------------------------------------------------------------------------'
    end
    def self.four
        puts ''
        puts ''
        puts ''
        puts '                                                   / \                 / \                 / \                 / \          '
        puts '                                                  |   |               |   |               |   |               |   |         '
        puts '                                                   \ /                 \ /                 \ /                 \ /          '
        puts '                                                    |                   |                   |                   |           '
        puts '                                                  / | \               / | \               / | \               / | \         '
        puts '                                                 /  |  \             /  |  \             /  |  \             /  |  \        '
        puts '                                                    |                   |                   |                   |           '
        puts '                                                   / \                 / \                 / \                 / \          '
        puts '                                                  /   \               /   \               /   \               /   \         '
        puts '                                                 /     \             /     \             /     \             /     \        '
        puts '                                        ------------------------------------------------------------------------------------'
    end
    def self.five
        puts ''
        puts ''
        puts ''
        puts '                                               / \               / \               / \               / \             / \    '
        puts '                                              |   |             |   |             |   |             |   |           |   |   '
        puts '                                               \ /               \ /               \ /               \ /             \ /    '
        puts '                                                |                 |                 |                 |               |     '
        puts '                                              / | \             / | \             / | \             / | \           / | \   '
        puts '                                             /  |  \           /  |  \           /  |  \           /  |  \         /  |  \  '
        puts '                                                |                 |                 |                 |               |     '
        puts '                                               / \               / \               / \               / \             / \    '
        puts '                                              /   \             /   \             /   \             /   \           /   \   '
        puts '                                             /     \           /     \           /     \           /     \         /     \  '
        puts '                                        ------------------------------------------------------------------------------------'
    end
end

