require_all './lib'
class Screen
    def self.welcome
        puts ''
        puts ''
        puts '                                                       \        / __      __  __  _   _  __    _____ __                      '
        puts '                                                        \  /\  / |__ |   |   |  | |\ /| |__      |  |  |                     '
        puts '                                                         \/  \/  |__ |__ |__ |__| | v | |__      |  |__|                     '
        puts '                                       _____                  _____                                                      _   '
        puts '                                      |  ___|                |  ___|                                                    | |  '
        puts '                                      | |        _   _____   | |     _____   _____    _  _    _   _   _   _____   ____  | |  '
        puts '                                      | |  ___  | | |__ __|  | |__  |  _  | |  _  |  | |/ /  | | | | | | |__ __| |  __| | |  '
        puts '                                      | | |_  | | |   | |    |  __| | | | | | |_| |  |   |   |  \| | | |   | |   | |__  |_|  '
        puts '                                      | |___| | | |   | |    | |    | |_| | | | \ \  | |\ \  | |\  | | |   | |   | |__   _   '
        puts '                                      |_______| |_|   |_|    |_|    |_____| |_|  \_\ |_| \_\ |_| \_| |_|   |_|   |____| |_|  '
        puts ''
        puts ''
        puts '                                                             Enter number of players between 2 and 5!'
        puts ''
    end
    def self.player_path
        puts ''
        puts ''
        puts '                                         Welcome, champion!         '
        puts '                                                                            / \               '
        puts '                                                                           |   |                                     '
        puts '                                                                            \ /                                      '
        puts '                                                                             |                                       '
        puts '                                                                           / | \                                     '
        puts '                                                                          /  |  \                                    '
        puts '                                                                             |                                       '
        puts '                                                                            / \                                      '
        puts '                                                                           /   \                                     '
        puts '                                                                          /     \                                    '
        puts '                                        ------------------------------------------------------------------------------------'
    end
    def self.new_player
        puts ''
        puts ''
        puts '                                         Welcome, new champion!         '
        puts '                                                                            / \       Please enter your name:        '
        puts '                                                                           |   |                                     '
        puts '                                                                            \ /                                      '
        puts '                                                                             |                                       '
        puts '                                                                           / | \                                     '
        puts '                                                                          /  |  \                                    '
        puts '                                                                             |                                       '
        puts '                                                                            / \                                      '
        puts '                                                                           /   \                                     '
        puts '                                                                          /     \                                    '
        puts '                                        ------------------------------------------------------------------------------------'
    end
    def self.weapon_selection                                                                                                            
        puts '                                                                            / \       Please choose two weapons:     '
        puts '                                                                           |   |                                     '
        puts '                                                                            \ /                                      '
        puts '                                                                        \/   |                                       '
        puts '                                                                         \__ | \                                     '
        puts '                                                                             |  \                                    '
        puts '                                                                             |                                       '
        puts '                                                                            / \                                      '
        puts '                                                                           /   \                                     '
        puts '                                                                          /     \                                    '
        puts '                                        ------------------------------------------------------------------------------------'
    end
    def self.spell_selection                                                                                                            
        puts '                                                                            / \       Please choose a spell:         '
        puts '                                                                           |   |                                     '
        puts '                                                                            \ /                                      '
        puts '                                                                        \    |                                       '
        puts '                                                                         \__ | \                                     '
        puts '                                                                             |  \                                    '
        puts '                                                                             |                                       '
        puts '                                                                            / \                                      '
        puts '                                                                           /   \                                     '
        puts '                                                                          /     \                                    '
        puts '                                        ------------------------------------------------------------------------------------'
    end
    def self.one                 
        puts '                                          _  _   _   ____    _    ____  _   _   ____   _____   __ _    _     _____  '
        puts '                                        _| || |_/ | | __ )  / \  / ___|| | | | |  _ \ / _ \ \ / // \  | |   | ____| '
        puts '                                       |_  ..  _| | |  _ \ / _ \ \___ \| |_| | | |_) | | | \ V // _ \ | |   |  _|   '
        puts '                                       |_      _| | | |_) / ___ \ ___) |  _  | |  _ <| |_| || |/ ___ \| |___| |___  '
        puts '                                         |_||_| |_| |____/_/   \_\____/|_| |_| |_| \_|\___/ |_/_/   \_\_____|_____| '                                                                          
        puts ''
        puts ''
        puts '                                                            / \                                                     '
        puts '                                                           |   |                                                    '
        puts '                                                            \ /                                                     '
        puts '                                                          \  |  /                                                   '
        puts '                                                           \ | /                                                    '
        puts '                                                             |                                                      '
        puts '                                                             |                        |                             '
        puts '                                                            / \          |            |      _ _ _                  '
        puts '                                                           /   \         |__ __ __ __ |_ __ /   X  \                '
        puts '                                                          /     \                           \_ _X _/                '
        puts '                                        ------------------------------------------------------------------------------------'
    end
    def self.two
        puts ''
        puts ''
        puts ''
        puts '                                                               / \                 / \                                      '
        puts '                                                              |   |               |   |                                     '
        puts '                                                               \ /                 \ /                                      '
        puts '                                                                |                   |                                       '
        puts '                                                              / | __ __       __ __ | \                                     '
        puts '                                                             /  |                   |  \                                    '
        puts '                                                                |                   |                                       '
        puts '                                                               / \                 / \                                      '
        puts '                                                              /   \               /   \                                     '
        puts '                                                             /     \             /     \                                    '
        puts '                                        ------------------------------------------------------------------------------------'
    end
    def self.three
        puts ''
        puts ''
        puts ''
        puts '                                                          / \                 / \                 / \                       '
        puts '                                                         |   |               |   |               |   |                      '
        puts '                                                          \ /                 \ /                 \ /                       '
        puts '                                                           |                   |                   |                        '
        puts '                                                         / | __ __       __ __ | __ __       __ __ | \                      '
        puts '                                                        /  |                   |                   |  \                     '
        puts '                                                           |                   |                   |                        '
        puts '                                                          / \                 / \                 / \                       '
        puts '                                                         /   \               /   \               /   \                      '
        puts '                                                        /     \             /     \             /     \                     '
        puts '                                        ------------------------------------------------------------------------------------'
    end
    def self.four
        puts ''
        puts ''
        puts ''
        puts '                                                   / \                 / \                 / \                 / \          '
        puts '                                                  |   |               |   |               |   |               |   |         '
        puts '                                                   \ /                 \ /                 \ /                 \ /          '
        puts '                                                    |                   |                   |                   |           '
        puts '                                                  / | __ __       __ __ | __ __       __ __ | __ __       __ __ | \         '
        puts '                                                 /  |                   |                   |                   |  \        '
        puts '                                                    |                   |                   |                   |           '
        puts '                                                   / \                 / \                 / \                 / \          '
        puts '                                                  /   \               /   \               /   \               /   \         '
        puts '                                                 /     \             /     \             /     \             /     \        '
        puts '                                        ------------------------------------------------------------------------------------'
    end
    def self.five
        puts ''
        puts ''
        puts ''
        puts '                                               / \               / \               / \               / \             / \    '
        puts '                                              |   |             |   |             |   |             |   |           |   |   '
        puts '                                               \ /               \ /               \ /               \ /             \ /    '
        puts '                                                |                 |                 |                 |               |     '
        puts '                                              / |__ __      __ __ | __ __     __ __ | __ __     __ __ | __ __   __ __ | \   '
        puts '                                             /  |                 |                 |                 |               |  \  '
        puts '                                                |                 |                 |                 |               |     '
        puts '                                               / \               / \               / \               / \             / \    '
        puts '                                              /   \             /   \             /   \             /   \           /   \   '
        puts '                                             /     \           /     \           /     \           /     \         /     \  '
        puts '                                        ------------------------------------------------------------------------------------'
    end
end

