Weapon.create(name: "Arming Sword", damage: 16)
Weapon.create(name: "Dagger", damage: 10)
Weapon.create(name: "Battle Axe", damage: 20)
Weapon.create(name: "War Hammer", damage: 15)
Weapon.create(name: "Crossbow", damage: 14 )
Weapon.create(name: "Musket", damage: 22 )
Weapon.create(name: "Javelin", damage: 30 )
Weapon.create(name: "Battering Club", damage: 8 )
Weapon.create(name: "Long Bow", damage: 18 )
Weapon.create(name: "Hand Cannon", damage: 24 )